### ISSUE TITLE
Bot fails to dump very long list of link

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/bxjs-weekly-bot#2]
`/dump` command fails with the following error:
```
(node:18) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: message is too long
       at buildConfig.then.then.then.then (/usr/src/app/node_modules/telegraf/core/network/client.js:263:17)
       at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Probably a good idea to see the message length limit on telegram and split result into multiple messages.

**Comment by yamalight** [comment]
Other edge case - zero links:
```
(node:19) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: message text is empty
       at buildConfig.then.then.then.then (/usr/src/app/node_modules/telegraf/core/network/client.js:263:17)
       at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
